In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score

In [2]:
df = pd.read_csv('heart_disease_health_indicators_BRFSS2015.csv')
df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,0.0,1.0,1.0,1.0,18.0,0.0,0.0,2.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,1.0,1.0,1.0,1.0,25.0,0.0,0.0,2.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [3]:
class Data_Generation(object):

    def __init__(self, dataset, size, data_type):
        self.dataset = dataset.copy().reset_index(drop = True)
        self.size = size
        self.data_type = data_type
        self.HighBP_nums = []
        self.HighChol_nums = []
        self.CholCheck_nums = []
        self.Smoker_nums = []
        self.Stroke_nums = []
        self.PhysActivity_nums = []
        self.Fruits_nums = []
        self.Veggies_nums= []
        self.HvyAlcoholConsump_nums = []
        self.AnyHealthcare_nums = []
        self.NoDocbcCost_nums = []
        self.DiffWalk_nums = []
        self.Sex_nums = []
        self.BMI_nums = []
        self.Diabetes_nums = []
        self.GenHlth_nums = []
        self.MentHlth_nums = []
        self.PhysHlth_nums = []
        self.Age_nums = []
        self.Education_nums = []
        self.Income_nums = []
        self.generated_data = []

    def generating_data(self):
        self.HighBP_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.HighChol_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.CholCheck_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Smoker_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Stroke_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.PhysActivity_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Fruits_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Veggies_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.HvyAlcoholConsump_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.AnyHealthcare_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.NoDocbcCost_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.DiffWalk_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Sex_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.BMI_nums = np.random.choice(range(12, 99), size=self.size).astype(self.data_type)
        self.Diabetes_nums = np.random.choice(range(0, 3), size = self.size).astype(self.data_type)
        self.GenHlth_nums = np.random.choice(range(1, 6), size = self.size).astype(self.data_type)
        self.MentHlth_nums = np.random.choice(range(0, 31), size = self.size).astype(self.data_type)
        self.PhysHlth_nums = np.random.choice(range(0, 31), size = self.size).astype(self.data_type)
        self.Age_nums = np.random.choice(range(1, 14), size = self.size).astype(self.data_type)
        self.Education_nums = np.random.choice(range(1, 7), size = self.size).astype(self.data_type)
        self.Income_nums = np.random.choice(range(1, 9), size = self.size).astype(self.data_type)
        
        
    def generating_dataframe(self):
        global generated_data_global

        self.generated_data = pd.DataFrame({"HighBP": self.HighBP_nums, 
                                            'HighChol': self.HighChol_nums,
                                            'CholCheck' : self.CholCheck_nums,
                                            'BMI' : self.BMI_nums, 
                                            'Smoker' : self.Smoker_nums, 
                                            'Stroke' : self.Stroke_nums, 
                                            'Diabetes' : self.Diabetes_nums,
                                            'PhysActivity' : self.PhysActivity_nums, 
                                            'Fruits' : self.Fruits_nums, 
                                            'Veggies' : self.Veggies_nums,
                                            'HvyAlcoholConsump' : self.HvyAlcoholConsump_nums, 
                                            'AnyHealthcare' : self.AnyHealthcare_nums, 
                                            'NoDocbcCost' : self.NoDocbcCost_nums,
                                            'GenHlth' : self.GenHlth_nums, 
                                            'MentHlth' : self.MentHlth_nums, 
                                            'PhysHlth' : self.PhysHlth_nums, 
                                            'DiffWalk' : self.DiffWalk_nums, 
                                            'Sex' : self.Sex_nums, 
                                            'Age' : self.Age_nums, 
                                            'Education' : self.Education_nums,
                                            'Income' : self.Income_nums})

        
        generated_data_global = self.generated_data

    def main(self):
        self.generating_data()
        self.generating_dataframe()

In [4]:
gen_df = Data_Generation(df, 1000000, float)

In [5]:
gen_df.main()

In [6]:
class Normalization(object):
    def __init__(self, dataset, dataset_prediction):
        self.dataset = dataset.copy().reset_index(drop = True)
        self.dataset_prediction = dataset_prediction.copy().reset_index(drop = True)
        self.df_max_scaled = dataset.copy()
        self.df_max_scaled_prediction = dataset_prediction.copy()
        self.df_min_max_scaled = dataset.copy()
        self.df_min_max_scaled_prediction = dataset_prediction.copy()
        self.z_scaled = dataset.copy()
        self.z_scaled_prediction = dataset_prediction.copy()
        self.column = ['HighBP', 'HighChol', 'CholCheck', 'BMI',
       'Smoker', 'Stroke', 'Diabetes', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income']
        
    def df_basic_def(self, dataset):
        global df_basic_global
        global df_prediction_basic_global
        
        df_basic = pd.DataFrame(index = self.dataset.columns, columns=['Min', 'Max', 'Sum', 'Mean', 'Mode'])
        df_basic['Min'] = self.dataset.min()
        df_basic['Max'] = self.dataset.max()
        df_basic['Sum'] = self.dataset.sum()
        df_basic['Mean'] = self.dataset.mean()
        df_basic['Mode'] = self.dataset.mode().T

        df_prediction_basic = pd.DataFrame(index = self.dataset_prediction.columns, columns=['Min', 'Max', 'Sum', 'Mean', 'Mode'])
        df_prediction_basic['Min'] = self.dataset_prediction.min()
        df_prediction_basic['Max'] = self.dataset_prediction.max()
        df_prediction_basic['Sum'] = self.dataset_prediction.sum()
        df_prediction_basic['Mean'] = self.dataset_prediction.mean()
        df_prediction_basic['Mode'] = self.dataset_prediction.mode().T
        
        df_basic_global = df_basic
        df_prediction_basic_global = df_prediction_basic

    def max_scaled(self):
        global df_max_scaled_global
        global df_max_scaled_prediction_global

        self.df_max_scaled[self.column] = self.df_max_scaled[self.column] / self.df_max_scaled[self.column].abs().max()
        self.df_max_scaled_prediction[self.column] = self.df_max_scaled_prediction[self.column] / self.df_max_scaled_prediction[self.column].abs().max()
        
        df_max_scaled_global = self.df_max_scaled
        df_max_scaled_prediction_global = self.df_max_scaled_prediction

    def min_max_scaled(self):
        global df_min_max_scaled_global
        global df_min_max_scaled_prediction_global
        
        self.df_min_max_scaled[self.column] = (self.df_min_max_scaled[self.column] - self.df_min_max_scaled[self.column].min()) / (self.df_min_max_scaled[self.column].max()  - self.df_min_max_scaled[self.column].min())
        self.df_min_max_scaled_prediction[self.column] = (self.df_min_max_scaled_prediction[self.column] - self.df_min_max_scaled_prediction[self.column].min()) / (self.df_min_max_scaled_prediction[self.column].max()  - self.df_min_max_scaled_prediction[self.column].min())
        
        df_min_max_scaled_global = self.df_min_max_scaled
        df_min_max_scaled_prediction_global = self.df_min_max_scaled_prediction

    def z_scaled_class(self):
        global z_scaled_global
        global z_scaled_prediction_global

        self.z_scaled[self.column] = (self.z_scaled[self.column] - self.z_scaled[self.column].mean()) / self.z_scaled[self.column].std()
        self.z_scaled_prediction[self.column] = (self.z_scaled_prediction[self.column] - self.z_scaled_prediction[self.column].mean()) / self.z_scaled_prediction[self.column].std()

        z_scaled_global = self.z_scaled
        z_scaled_prediction_global = self.z_scaled_prediction

    def main(self):
        self.df_basic_def(self.dataset)
        self.max_scaled()
        self.min_max_scaled()
        self.z_scaled_class()

In [7]:
norm = Normalization(df, generated_data_global)

In [8]:
norm.main()

In [9]:
class Classification(object):
    def __init__(self, dataset, dataset_prediction, label, test_size, random_state, shuffle, stratify, max_iter_LR, random_state_LR):
        self.dataset = dataset.copy().reset_index(drop = True)
        self.dataset_prediction = dataset_prediction.copy().reset_index(drop = True)
        self.X = self.dataset.drop([label], axis = 1)
        self.y = self.dataset[[label]].copy()
        self.label = label
        self.test_size = test_size
        self.random_state = random_state
        self.shuffle = shuffle
        self.stratify = stratify
        self.max_iter_LR = max_iter_LR
        self.random_state_LR = random_state_LR

        

    def train_test_split_def(self):

        global X_train, X_test, y_train, y_test
        
        X_train, X_test, y_train, y_test = train_test_split(self.X, self.y , test_size=self.test_size, random_state=self.random_state)


    def LogisticRegression(self):
        
        global df_prediction_LR_global
        
        model = LogisticRegression(max_iter = self.max_iter_LR, random_state =  self.random_state_LR)
        model.fit(X_train, np.ravel(y_train))

        predictions = model.predict(X_test)
        
        cm = confusion_matrix(y_test, predictions)
        
        TN, FP, FN, TP = confusion_matrix(y_test, predictions).ravel()

        print("Logistic Regression's confusion matrix: ")
        print('True Positive(TP)  = ', TP)
        print('False Positive(FP) = ', FP)
        print('True Negative(TN)  = ', TN)
        print('False Negative(FN) = ', FN)

        acc = accuracy_score(y_test, predictions) * 100
        print(f"Logistic Regression model accuracy: {acc:.2f}%")
        precision = precision_score(predictions, y_test) * 100
        print(f"Logistic Regression model precision: {precision:.2f}%")
        recall = recall_score(predictions, y_test) * 100
        print(f"Logistic Regression model recall: {recall:.2f}%")
        print('\n')

        df_prediction_LR = self.dataset_prediction.copy()
        df_prediction_LR['HeartDiseaseorAttack'] = model.predict(self.dataset_prediction.copy())
        df_prediction_LR_global = df_prediction_LR
        
    def LinearSVC(self):
        global df_prediction_SVC_global
        
        model = LinearSVC(random_state = 0, tol = 1e-5)
        model.fit(X_train, np.ravel(y_train))

        predictions = model.predict(X_test)

        cm = confusion_matrix(y_test, predictions)
        TN, FP, FN, TP = confusion_matrix(y_test, predictions).ravel()

        print("Linear Support Vector Classification's confusion matrix: ")
        print('True Positive(TP)  = ', TP)
        print('False Positive(FP) = ', FP)
        print('True Negative(TN)  = ', TN)
        print('False Negative(FN) = ', FN)
        
        acc = accuracy_score(y_test, predictions) * 100
        print(f"Linear Support Vector Classification model accuracy: {acc:.2f}%")
        precision = precision_score(predictions, y_test) * 100
        print(f"Linear Support Vector Classification model precision: {precision:.2f}%")
        recall = recall_score(predictions, y_test) * 100
        print(f"Linear Support Vector Classification model recall: {recall:.2f}%")
        print('\n')

        df_prediction_SVC = self.dataset_prediction.copy()
        df_prediction_SVC['HeartDiseaseorAttack'] = model.predict(self.dataset_prediction.copy())
        df_prediction_SVC_global = df_prediction_SVC
        

    def Decision_tree(self):
        global df_prediction_Decision_tree_global
        
        model = DecisionTreeClassifier()
        model.fit(X_train, np.ravel(y_train))

        predictions = model.predict(X_test)

        cm = confusion_matrix(y_test, predictions)
        TN, FP, FN, TP = confusion_matrix(y_test, predictions).ravel()

        print("Decision Tree Classifier's confusion matrix: ")
        print('True Positive(TP)  = ', TP)
        print('False Positive(FP) = ', FP)
        print('True Negative(TN)  = ', TN)
        print('False Negative(FN) = ', FN)
        
        acc = accuracy_score(y_test, predictions) * 100
        print(f"Decision Tree Classifier model accuracy: {acc:.2f}%")
        precision = precision_score(predictions, y_test) * 100
        print(f"Decision Tree Classifier model precision: {precision:.2f}%")
        recall = recall_score(predictions, y_test) * 100
        print(f"Decision Tree Classifier model recall: {recall:.2f}%")
        print('\n')

        df_prediction_Decision_tree = self.dataset_prediction.copy()
        df_prediction_Decision_tree['HeartDiseaseorAttack'] = model.predict(self.dataset_prediction.copy())
        df_prediction_Decision_tree_global = df_prediction_Decision_tree

    def Random_forest(self):
        global df_prediction_RandomForest_global
        
        model = RandomForestClassifier(n_estimators = 10)
        model.fit(X_train, np.ravel(y_train))

        predictions = model.predict(X_test)

        cm = confusion_matrix(y_test, predictions)
        TN, FP, FN, TP = confusion_matrix(y_test, predictions).ravel()

        print("Random Forest Classifier's confusion matrix: ")
        print('True Positive(TP)  = ', TP)
        print('False Positive(FP) = ', FP)
        print('True Negative(TN)  = ', TN)
        print('False Negative(FN) = ', FN)
        
        acc = accuracy_score(y_test, predictions) * 100
        print(f"Random Forest Classifier model accuracy: {acc:.2f}%")
        precision = precision_score(predictions, y_test) * 100
        print(f"Random Forest Classifier model precision: {precision:.2f}%")
        recall = recall_score(predictions, y_test) * 100
        print(f"Random Forest Classifier model recall: {recall:.2f}%")
        print('\n')

        df_prediction_RandomForest = self.dataset_prediction.copy()
        df_prediction_RandomForest['HeartDiseaseorAttack'] = model.predict(self.dataset_prediction.copy())
        df_prediction_RandomForest_global = df_prediction_RandomForest

    def Naive_Bayes(self):
        global df_prediction_naive_bayes_global

        model = GaussianNB()
        model.fit(X_train, np.ravel(y_train))

        predictions = model.predict(X_test)

        cm = confusion_matrix(y_test, predictions)
        TN, FP, FN, TP = confusion_matrix(y_test, predictions).ravel()

        print("Naive Bayes's confusion matrix: ")
        print('True Positive(TP)  = ', TP)
        print('False Positive(FP) = ', FP)
        print('True Negative(TN)  = ', TN)
        print('False Negative(FN) = ', FN)
        
        acc = accuracy_score(y_test, predictions) * 100
        print(f"Naive Bayes model accuracy: {acc:.2f}%")
        precision = precision_score(predictions, y_test) * 100
        print(f"Naive Bayes model precision: {precision:.2f}%")
        recall = recall_score(predictions, y_test) * 100
        print(f"Naive Bayes model recall: {recall:.2f}%")
        print('\n')

        df_prediction_naive_bayes = self.dataset_prediction.copy()
        df_prediction_naive_bayes['HeartDiseaseorAttack'] = model.predict(self.dataset_prediction.copy())
        df_prediction_naive_bayes_global = df_prediction_naive_bayes

    def K_Nearest_Neighbours(self):
        global df_prediction_KNearestNeighbours_global

        model = KNeighborsClassifier()
        model.fit(X_train, np.ravel(y_train))

        predictions = model.predict(X_test)

        cm = confusion_matrix(y_test, predictions)
        TN, FP, FN, TP = confusion_matrix(y_test, predictions).ravel()

        print("K Nearest Neighbours' confusion matrix: ")
        print('True Positive(TP)  = ', TP)
        print('False Positive(FP) = ', FP)
        print('True Negative(TN)  = ', TN)
        print('False Negative(FN) = ', FN)
        
        acc = accuracy_score(y_test, predictions) * 100
        print(f"K Nearest Neighbours model accuracy: {acc:.2f}%")
        precision = precision_score(predictions, y_test) * 100
        print(f"K Nearest Neighbours model precision: {precision:.2f}%")
        recall = recall_score(predictions, y_test) * 100
        print(f"K Nearest Neighbours model recall: {recall:.2f}%")
        print('\n')

        df_prediction_KNearestNeighbours = self.dataset_prediction.copy()
        df_prediction_KNearestNeighbours['HeartDiseaseorAttack'] = model.predict(self.dataset_prediction.copy())
        df_prediction_KNearestNeighbours_global = df_prediction_KNearestNeighbours
        
    def main(self):
        self.train_test_split_def()
        self.LogisticRegression()
        self.LinearSVC()
        self.Decision_tree()
        self.Random_forest()
        self.Naive_Bayes()
        self.K_Nearest_Neighbours()

In [10]:
CL = Classification(df, generated_data_global, 'HeartDiseaseorAttack', 0.20, 0, True, None, 10000, 0)

In [11]:
CL.main()

Logistic Regression's confusion matrix:
True Positive(TP)  =  688
False Positive(FP) =  509
True Negative(TN)  =  45455
False Negative(FN) =  4084
Logistic Regression model accuracy: 90.95%
Logistic Regression model precision: 14.42%
Logistic Regression model recall: 57.48%


Linear Support Vector Classification's confusion matrix:
True Positive(TP)  =  254
False Positive(FP) =  120
True Negative(TN)  =  45844
False Negative(FN) =  4518
Linear Support Vector Classification model accuracy: 90.86%
Linear Support Vector Classification model precision: 5.32%
Linear Support Vector Classification model recall: 67.91%


Decision Tree Classifier's confusion matrix:
True Positive(TP)  =  1349
False Positive(FP) =  4151
True Negative(TN)  =  41813
False Negative(FN) =  3423
Decision Tree Classifier model accuracy: 85.07%
Decision Tree Classifier model precision: 28.27%
Decision Tree Classifier model recall: 24.53%


Random Forest Classifier's confusion matrix:
True Positive(TP)  =  568
False Positive(FP) =  878
True Negative(TN)  =  45086
False Negative(FN) =  4204
Random Forest Classifier model accuracy: 89.98%
Random Forest Classifier model precision: 11.90%
Random Forest Classifier model recall: 39.28%


Naive Bayes's confusion matrix:
True Positive(TP)  =  2631
False Positive(FP) =  6956
True Negative(TN)  =  39008
False Negative(FN) =  2141
Naive Bayes model accuracy: 82.07%
Naive Bayes model precision: 55.13%
Naive Bayes model recall: 27.44%


K Nearest Neighbours' confusion matrix:
True Positive(TP)  =  526
False Positive(FP) =  1047
True Negative(TN)  =  44917
False Negative(FN) =  4246
K Nearest Neighbours model accuracy: 89.57%
K Nearest Neighbours model precision: 11.02%
K Nearest Neighbours model recall: 33.44%

In [12]:
df_prediction_LR_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,0.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,0.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,0.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,0.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,0.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,0.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,0.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,0.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,0.0

In [13]:
df_prediction_SVC_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,0.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,0.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,0.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,0.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,0.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,0.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,0.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,0.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,0.0

In [14]:
df_prediction_Decision_tree_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,1.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,0.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,0.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,0.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,1.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,1.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,1.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,0.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,0.0

In [15]:
df_prediction_RandomForest_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,0.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,0.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,0.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,0.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,0.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,0.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,1.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,0.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,0.0

In [16]:
df_prediction_naive_bayes_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,0.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,0.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,0.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,0.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,0.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,1.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,1.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,1.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,0.0

In [17]:
df_prediction_KNearestNeighbours_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,0.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,0.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,0.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,0.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,0.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,0.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,0.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,0.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,0.0

In [18]:
CL_1 = Classification(df_max_scaled_global, generated_data_global, 'HeartDiseaseorAttack', 0.20, 0, True, None, 10000, 0)

In [19]:
CL_1.main()

Logistic Regression's confusion matrix:
True Positive(TP)  =  690
False Positive(FP) =  507
True Negative(TN)  =  45457
False Negative(FN) =  4082
Logistic Regression model accuracy: 90.96%
Logistic Regression model precision: 14.46%
Logistic Regression model recall: 57.64%


Linear Support Vector Classification's confusion matrix:
True Positive(TP)  =  254
False Positive(FP) =  120
True Negative(TN)  =  45844
False Negative(FN) =  4518
Linear Support Vector Classification model accuracy: 90.86%
Linear Support Vector Classification model precision: 5.32%
Linear Support Vector Classification model recall: 67.91%


Decision Tree Classifier's confusion matrix:
True Positive(TP)  =  1350
False Positive(FP) =  4172
True Negative(TN)  =  41792
False Negative(FN) =  3422
Decision Tree Classifier model accuracy: 85.03%
Decision Tree Classifier model precision: 28.29%
Decision Tree Classifier model recall: 24.45%


Random Forest Classifier's confusion matrix:
True Positive(TP)  =  568
False Positive(FP) =  959
True Negative(TN)  =  45005
False Negative(FN) =  4204
Random Forest Classifier model accuracy: 89.82%
Random Forest Classifier model precision: 11.90%
Random Forest Classifier model recall: 37.20%


Naive Bayes's confusion matrix:
True Positive(TP)  =  2631
False Positive(FP) =  6956
True Negative(TN)  =  39008
False Negative(FN) =  2141
Naive Bayes model accuracy: 82.07%
Naive Bayes model precision: 55.13%
Naive Bayes model recall: 27.44%


K Nearest Neighbours' confusion matrix:
True Positive(TP)  =  779
False Positive(FP) =  1229
True Negative(TN)  =  44735
False Negative(FN) =  3993
K Nearest Neighbours model accuracy: 89.71%
K Nearest Neighbours model precision: 16.32%
K Nearest Neighbours model recall: 38.79%

In [20]:
df_prediction_LR_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,1.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,1.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,1.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,1.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,1.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,1.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,1.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,1.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,1.0

In [21]:
df_prediction_SVC_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,1.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,1.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,1.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,0.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,1.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,0.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,0.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,1.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,0.0

In [22]:
df_prediction_Decision_tree_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,0.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,1.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,0.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,0.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,0.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,0.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,0.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,0.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,0.0

In [23]:
df_prediction_RandomForest_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,0.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,0.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,0.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,0.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,0.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,0.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,0.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,0.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,0.0

In [24]:
df_prediction_naive_bayes_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,1.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,1.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,1.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,1.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,1.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,1.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,1.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,1.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,1.0

In [25]:
df_prediction_KNearestNeighbours_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,1.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,1.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,1.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,1.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,0.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,0.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,1.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,1.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,1.0

In [26]:
CL_2 = Classification(df_min_max_scaled_global, generated_data_global, 'HeartDiseaseorAttack', 0.20, 0, True, None, 10000, 0)

In [27]:
CL_2.main()

Logistic Regression's confusion matrix:
True Positive(TP)  =  689
False Positive(FP) =  510
True Negative(TN)  =  45454
False Negative(FN) =  4083
Logistic Regression model accuracy: 90.95%
Logistic Regression model precision: 14.44%
Logistic Regression model recall: 57.46%


Linear Support Vector Classification's confusion matrix:
True Positive(TP)  =  254
False Positive(FP) =  120
True Negative(TN)  =  45844
False Negative(FN) =  4518
Linear Support Vector Classification model accuracy: 90.86%
Linear Support Vector Classification model precision: 5.32%
Linear Support Vector Classification model recall: 67.91%


Decision Tree Classifier's confusion matrix:
True Positive(TP)  =  1331
False Positive(FP) =  4138
True Negative(TN)  =  41826
False Negative(FN) =  3441
Decision Tree Classifier model accuracy: 85.06%
Decision Tree Classifier model precision: 27.89%
Decision Tree Classifier model recall: 24.34%


Random Forest Classifier's confusion matrix:
True Positive(TP)  =  584
False Positive(FP) =  960
True Negative(TN)  =  45004
False Negative(FN) =  4188
Random Forest Classifier model accuracy: 89.85%
Random Forest Classifier model precision: 12.24%
Random Forest Classifier model recall: 37.82%


Naive Bayes's confusion matrix:
True Positive(TP)  =  2631
False Positive(FP) =  6956
True Negative(TN)  =  39008
False Negative(FN) =  2141
Naive Bayes model accuracy: 82.07%
Naive Bayes model precision: 55.13%
Naive Bayes model recall: 27.44%


K Nearest Neighbours' confusion matrix:
True Positive(TP)  =  756
False Positive(FP) =  1227
True Negative(TN)  =  44737
False Negative(FN) =  4016
K Nearest Neighbours model accuracy: 89.67%
K Nearest Neighbours model precision: 15.84%
K Nearest Neighbours model recall: 38.12%

In [28]:
df_prediction_LR_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,1.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,1.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,1.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,1.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,1.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,1.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,1.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,1.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,1.0

In [29]:
df_prediction_SVC_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,1.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,1.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,1.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,0.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,1.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,0.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,0.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,1.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,0.0

In [30]:
df_prediction_Decision_tree_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,0.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,1.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,0.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,0.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,0.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,0.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,0.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,0.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,0.0

In [31]:
df_prediction_RandomForest_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,0.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,0.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,0.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,0.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,0.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,0.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,1.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,0.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,0.0

In [32]:
df_prediction_naive_bayes_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,1.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,1.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,1.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,1.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,1.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,1.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,1.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,1.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,1.0

In [33]:
df_prediction_KNearestNeighbours_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,1.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,1.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,1.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,1.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,0.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,0.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,1.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,1.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,1.0

In [34]:
CL_3 = Classification(z_scaled_global, generated_data_global, 'HeartDiseaseorAttack', 0.20, 0, True, None, 10000, 0)

In [35]:
CL_3.main()

Logistic Regression's confusion matrix:
True Positive(TP)  =  690
False Positive(FP) =  508
True Negative(TN)  =  45456
False Negative(FN) =  4082
Logistic Regression model accuracy: 90.95%
Logistic Regression model precision: 14.46%
Logistic Regression model recall: 57.60%


Linear Support Vector Classification's confusion matrix:
True Positive(TP)  =  254
False Positive(FP) =  120
True Negative(TN)  =  45844
False Negative(FN) =  4518
Linear Support Vector Classification model accuracy: 90.86%
Linear Support Vector Classification model precision: 5.32%
Linear Support Vector Classification model recall: 67.91%


Decision Tree Classifier's confusion matrix:
True Positive(TP)  =  1357
False Positive(FP) =  4119
True Negative(TN)  =  41845
False Negative(FN) =  3415
Decision Tree Classifier model accuracy: 85.15%
Decision Tree Classifier model precision: 28.44%
Decision Tree Classifier model recall: 24.78%


Random Forest Classifier's confusion matrix:
True Positive(TP)  =  638
False Positive(FP) =  909
True Negative(TN)  =  45055
False Negative(FN) =  4134
Random Forest Classifier model accuracy: 90.06%
Random Forest Classifier model precision: 13.37%
Random Forest Classifier model recall: 41.24%


Naive Bayes's confusion matrix:
True Positive(TP)  =  2631
False Positive(FP) =  6956
True Negative(TN)  =  39008
False Negative(FN) =  2141
Naive Bayes model accuracy: 82.07%
Naive Bayes model precision: 55.13%
Naive Bayes model recall: 27.44%


K Nearest Neighbours' confusion matrix:
True Positive(TP)  =  772
False Positive(FP) =  1221
True Negative(TN)  =  44743
False Negative(FN) =  4000
K Nearest Neighbours model accuracy: 89.71%
K Nearest Neighbours model precision: 16.18%
K Nearest Neighbours model recall: 38.74%

In [36]:
df_prediction_LR_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,1.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,1.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,1.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,1.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,1.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,1.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,1.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,1.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,1.0

In [37]:
df_prediction_SVC_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,1.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,1.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,1.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,1.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,1.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,0.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,1.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,1.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,1.0

In [38]:
df_prediction_Decision_tree_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,0.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,1.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,1.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,0.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,0.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,0.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,0.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,1.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,0.0

In [39]:
df_prediction_RandomForest_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,0.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,0.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,0.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,0.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,1.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,0.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,0.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,0.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,0.0

In [40]:
df_prediction_naive_bayes_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,1.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,1.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,1.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,1.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,1.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,1.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,1.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,1.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,1.0

In [41]:
df_prediction_KNearestNeighbours_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,0.0,0.0,0.0,48.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,5.0,26.0,26.0,0.0,0.0,11.0,3.0,3.0,0.0
1,0.0,0.0,1.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,5.0,18.0,1.0,0.0,1.0,7.0,3.0,4.0,1.0
2,1.0,1.0,0.0,52.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,21.0,29.0,0.0,0.0,7.0,3.0,4.0,0.0
3,1.0,0.0,0.0,95.0,1.0,1.0,2.0,0.0,1.0,0.0,...,1.0,5.0,28.0,9.0,1.0,0.0,6.0,4.0,8.0,1.0
4,1.0,0.0,0.0,83.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,18.0,2.0,0.0,1.0,10.0,5.0,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1.0,0.0,0.0,18.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,28.0,28.0,0.0,1.0,7.0,2.0,4.0,1.0
999996,1.0,0.0,1.0,32.0,1.0,1.0,2.0,1.0,0.0,0.0,...,1.0,2.0,24.0,3.0,1.0,0.0,3.0,4.0,7.0,1.0
999997,0.0,1.0,1.0,80.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,3.0,19.0,8.0,1.0,1.0,5.0,3.0,4.0,1.0
999998,1.0,1.0,1.0,80.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,4.0,10.0,8.0,0.0,0.0,10.0,3.0,6.0,0.0
999999,1.0,0.0,0.0,82.0,1.0,0.0,2.0,1.0,0.0,0.0,...,0.0,2.0,20.0,8.0,0.0,1.0,6.0,6.0,5.0,1.0